name: Desafio ChapterIV

#gatilhos
on:
  push:
    branches: [ main ]

jobs:
  build:
  
  
#maquina ou ambiente
    runs-on: ubuntu-latest
    
    
#passos
    steps:
    
#downsload do codigo    
    - uses: actions/checkout@v2
    
#setup da versÃ£o do node
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        
    - run: npm install
    - run: npm run cy:run
      continue-on-error: true
    - run: npm run report:merge
    - run: npm run report:mocha
    
#github pages > publicar o relatorio
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh_pages
        FOLDER: mochawesome-report
